### ISSUE TITLE
error: expected unqualified-id before this

### ISSUE THREAD

**Issue by iyevugah** [thelfer/tfel#126]
Hello, I’m re-implementing the trivial Von Mises Model using the Implicit DSL domain. An implementation of this model already exist here: https://thelfer.github.io/tfel/web/IsotropicLinearHardeningPlasticity.html. However, the current implementation is based on the Default Domain. 

I ran into a few errors with my implementation (please see the attached files and my code) which is based on similar approach used in http://tfel.sourceforge.net/MohrCoulomb.html#simplification-of-the-mfront-file-use-of-tfelmaterialmohrcoulombyieldcriterion.hxx-file. 

I will be grateful if you can please help me out. Thanks.

[myCode.txt](https://github.com/thelfer/tfel/files/8127257/myCode.txt)

![Capture](https://user-images.githubusercontent.com/73094448/155394418-8f6078da-0dad-42b0-a657-6510b426fee8.PNG)
![Capture 2](https://user-images.githubusercontent.com/73094448/155394430-a174c629-f662-4497-a7f5-4ff8881eda30.PNG)

**Comment by thelfer** [comment]
Hi @iyevugah,

You probably fell on one of the most vexing error report when using MFront, basically because this error is generated by the C++ compiler and do not provide much context about what is wrong in your code. Before telling you what is is, let us analyse the error message:

~~~~
Vm2.mfront:46:12: error: expected unqualified-id before ‘this’
~~~~

The error happens at line 46 column 12 of your `MFront` file, which is:

~~~~
const auto F = seq_e > s0 + H * lam;
~~~~

which indicates something wrong with the declaration of a new variable `F`.

You could now have compiled the file in debug mode to see the error in the generated file, not in the `MFront` source file:

~~~~
$ $ mfront --obuild --debug --interface=generic test.mfront 
Treating target : all
make : on entre dans le répertoire « /tmp/src »
In file included from Vm2-generic.cxx:27:
../include/TFEL/Material/Vm2.hxx: In member function ‘void tfel::material::Vm2<hypothesis, NumericType, false>::initialize()’:
../include/TFEL/Material/Vm2.hxx:468:12: error: expected unqualified-id before ‘this’
 const auto this->F = seq_e > this->s0 + this->H * this->lam;
            ^~~~
~~~~

which shows that `MFront` added `this->` before `F`. `MFront` does that because `F` has previously been declared as a local variable, see line 32 of your `MFront` file:

~~~~
@LocalVariable bool F; // if true, plastic loading
~~~~

Internally, `F` is declared as a data member of the `Vm2` class. For technical reasons related to `C++`, `MFront` automatically adds `this->` in front of every data member.

This has the following consequence: one cannot declare a variable with the name of an `MFront` variable. This is very sound, IMHO, but the error message is obviously awfull.

**Comment by iyevugah** [comment]
Perfect, It works!! See below. 

Thanks a lot @thelfer. Before, I run the Mtest, I just want to know what you think about my approach/solution? TBH, I'm not entirely confident with my implementation. Is my approach correct? I am I on the right path? Thanks. 

![Capture3](https://user-images.githubusercontent.com/73094448/155401003-ddb83603-18c8-4036-aa3f-8bd589996c85.PNG)

**Comment by thelfer** [comment]
If I make the suggested correction, I got other errors. Would you attach the lastest version of your file ?

**Comment by iyevugah** [comment]
Sure, Here it is: 
[myCode.txt](https://github.com/thelfer/tfel/files/8127575/myCode.txt)

**Comment by thelfer** [comment]
There were a few mistakes. For example, you used the computeElasticPrediction in the `@Integrator` block, which does not make sense.

See this corrected file with some advices: [test.zip](https://github.com/thelfer/tfel/files/8127897/test.zip)

Note that I did not test it, so there is no warranty.

**Comment by iyevugah** [comment]
Great! I have tested it and it works! See below: I really appreciate the comments. Thank you.  Now I'm confident I can implement my own model and test it. 👍 

![vm2](https://user-images.githubusercontent.com/73094448/155426371-aded1180-95a3-4e0f-8d14-041c3991b97c.PNG)

![von mises](https://user-images.githubusercontent.com/73094448/155426382-a580c6be-fa09-4eb7-a8f9-b1ea0f4795ff.PNG)
