### ISSUE TITLE
Material elasticity tensor

### ISSUE THREAD

**Issue by mprasad-simscale** [thelfer/tfel#418]
Hello everyone,

The consistent tangent operator according to MFront (defined [here](https://tfel.sourceforge.net/signorini.html)) is: CE = dS/dC
However the fourth order material elasticity tensor is defined as: CE=2*(dS/dC)

The pre-multiplication factor 2 is missing the MFront definition, is this considered internally somehow?

**Comment by thelfer** [comment]
Hi @mprasad-simscale,

You can define the consistent tangent operator is numerous ways in your implementation and  `MFront` will take car of the  conversion to the consistent tangent operator expected by the interface that you are using.

See the Figure "Relation between tangent operators" in [this page](https://tfel.sourceforge.net/ansys.html)

Best,

Thomas

**Comment by mprasad-simscale** [comment]
Thanks for the quick reply Thomas. The interface I use is code_aster, and according to code_aster's [documentation](https://code-aster.org/V2/doc/v13/en/man_r/r5/r5.03.19.pdf) the elasticity tensor is defined as: CE=2*(dS/dC).

Just for clarity: (considering interface=aster) once dS/dC is computed, should I use: 
@TangentOperator<DS_DC>{
  static_cast<void>(smt);
  Dt = dS_dC;
}
 or this:
@TangentOperator<DS_DC>{
  static_cast<void>(smt);
  Dt = 2*dS_dC;
}

**Comment by thelfer** [comment]
You should use!

~~~~{.cxx}
@TangentOperator<DS_DC>{
  static_cast<void>(smt);
  Dt = dS_dC;
}
~~~~

or:

~~~~{.cxx}
@TangentOperator<DS_DEGL>{
  static_cast<void>(smt);
  Dt = 2 * dS_dC;
}
~~~~

Note that you can use both: `MFront` will select the one that requires the less transformation for the tangent operator requested by the interface.

In the specific case of the  `aster` interface, the `DS_DEGL` will be used directly (if you use the `TotalLagrangian` option, otherwise a more complex tangent operator is used. See the "Finite strain behaviors" section of [this page](https://thelfer.github.io/tfel/web/aster.htmlà

**Comment by thelfer** [comment]
@mprasad-simscale Could we close this issue ?
