### ISSUE TITLE
[mtest] Add support for a boundary condition modelling the effet of a mandrel in pipe modelling

### ISSUE THREAD

**Issue by fabonimus** [thelfer/tfel#44]
Dear Thomas,
Following my previous issue, when using the pipe modelling module `PTest` in `MTest`, I would like to be able to activate/desactivate boundary conditions.

More precisely, I would like to apply :+1: 

1) first a constant pressure on the outer radius of the tube and
2) then apply a constant strain rate on the inner radius of the tube.

With my best regards,
Fabien Onimus

**Comment by thelfer** [comment]
Hi @fabonimus,

Rather than this very generic feature, which is difficult to handle, I wonder if we shall not try to reproduce the boundary conditions of most fuel performance codes.

What do you think of the following syntax:

@RadialLoading 'Mandrel';
@MandrelOuterRadiusEvolution<> ...;

We could optionnally define the mandrel axial growth to impose that the increment of the axial growth of the pipe is equal to the increment of the axial growth of the mandrel after the contact is established:

@MandrelAxialGrowthEvolution<> ...;

Would you be ok with this proposal ?

Thomas

**Comment by fabonimus** [comment]
Dear Thomas,
this sounds great. This is a good idea.
Thank you again very much,
Fabien

**Comment by thelfer** [comment]
Great ! I'll try to do this ASAP.
But you'll need to carefully validate those developments.

**Comment by thelfer** [comment]
he effect of a mandrel located inside the pipe can be modelled by
defining the evolution of its radius \(R_{m}\) using the
`@MandrelRadiusEvolution` keyword. The inner radius \(R_{i}\) will then
satisfy the following unilateral boundary condition:

\[
R_{i} - R_{m} \geq 0
\]

This boundary condition is imposed by using a Lagrange multiplier. Its
value is given by the contact pressure in the output file. The total
pressure applied to the inner surface of the pipe is given by the sum of
the imposed pressure (if any) and the contact pressure. Only the imposed
inner pressure is used to compute the end cap effect.

This boundary condition is not compatible with:

- boundary conditions imposing the evolution of the inner radius of the
  pipe or the outer radius of the pipe.
- the modelling of a tight pipe. 

### Axial binding

If the evolution of the axial growth of the mandrel is defined using the
`@MandrelAxialGrowthEvolution` keyword, an axial binding between the
mandrel and the pipe is assumed, i.e. the difference between the axial
growth of the pipe \(\varepsilon^{p}_{zz}\) and the axial growth of the
mandrel \(\varepsilon^{p}_{zz}\) is assumed to be constant to its value
when the contact between the mandrel and the pipe is detected:

\[
\varepsilon^{p}_{zz}-\varepsilon^{m}_{zz}=\textrm{Cste}
\]

This axial boundary condition is not compatible with the boundary
condition imposing the evolution of the axial growth of the pipe.
