### ISSUE TITLE
[MTEST] Impossible to run MTEST with BRICK using ASTER 

### ISSUE THREAD

**Issue by arinamarchenko2021** [thelfer/tfel#52]
Hello Thomas,
I am having a problem trying to run MTEST (simple tensile test) with Code_Aster (ldcASTER.mtest), the behavior is simple written with StandardElastoViscoPlasticity Brick (ldc.mfront). The obtained message error is: 

 _what():  SingleStructureSchemeParser::SingleStructureScheme : error while parsing file 'ldcASTER.mtest' at line '2'.
Behaviour::getBehaviour: unsupported behaviour kinematic_

I tried to run the same MTEST with UMAT (ldcUMAT.mtest) and it finishes successfully. 

Three files are attached to this issue.

Thank you in advance for any ideas and suggestions.

Arina 

[ldc.zip](https://github.com/thelfer/tfel/files/7693235/ldc.zip)

**Comment by thelfer** [comment]
Hi @arinamarchenko2021,

This is one caveat with the `aster` interface regarding logarithmic strain.

As `code_aster` does handle the logarithmic strain framework internally,  `mtest` complains that he can't handle this behaviour because he does not handle the  logarithmic strain framework.

This can be better understood if we compare to what happens if one uses the `generic` or the `Cast3M` interface. In those cases, the generated behaviours does handle the  logarithmic strain framework internally and what `MTest` "sees"  is just a regular finite strain behaviour.

So, its not really an `MTest` bug, but a limitation.

Thomas

P.S. Your example showed me that there is a bug in TFEL-4.0. See https://github.com/thelfer/tfel/issues/53
